// backend/src/services/voiceAgent.service.js
// Phase 3.1 — Stub agent. Connects to a LiveKit room as a server-side participant.
//
// SDK DECISION:
//   - `livekit-client` is BROWSER-ONLY — it depends on WebRTC APIs not available in Node.js.
//   - `@livekit/rtc-node` is the correct server-side SDK for Node.js room participation.
//   - If @livekit/rtc-node fails to load (native bindings missing on Windows),
//     the service runs in "token-only" mode — tokens are generated, but the agent
//     does NOT join the room. The server does NOT crash.

import livekitService from './livekit.service.js';

// --- C2 FIX: Dynamic import with graceful fallback ---
let Room = null;
let RoomEvent = null;
let rtcAvailable = false;

try {
  const rtcModule = await import('@livekit/rtc-node');
  Room = rtcModule.Room;
  RoomEvent = rtcModule.RoomEvent;
  rtcAvailable = true;
  console.log('[VoiceAgent] ✅ @livekit/rtc-node loaded successfully');
} catch (err) {
  console.warn('[VoiceAgent] ⚠️ @livekit/rtc-node not available:', err.message);
  console.warn('[VoiceAgent] Running in token-only mode — agent will NOT join rooms.');
}

class VoiceAgentService {
  constructor() {
    this._activeSessions = new Map();
  }

  /**
   * Start a voice session: the Node agent joins the specified LiveKit room.
   * Phase 3.1 stub — logs connection events, no audio processing.
   *
   * If @livekit/rtc-node is not available, logs a warning and returns
   * without joining. The token is still generated by the route handler.
   *
   * @param {string} roomName - LiveKit room to join
   * @param {object} [options]
   * @param {number} [options.timeoutMs=120000] - Max session duration (auto-disconnect)
   * @returns {Promise<{roomName: string, status: string}>}
   */
  async startVoiceSession(roomName, options = {}) {
    if (!rtcAvailable) {
      console.warn(`[VoiceAgent] Skipping room join for ${roomName} — native module not loaded.`);
      return { roomName, status: 'token_only' };
    }

    const timeoutMs = options.timeoutMs || 120_000;

    console.log(`[VoiceAgent] Starting session for room: ${roomName}`);

    // 1. Generate agent token
    let token;
    try {
      token = await livekitService.createRoomToken(roomName, 'node-agent', {
        canPublish: true,
        canSubscribe: true,
      });
    } catch (err) {
      console.error(`[VoiceAgent] Token generation failed:`, err.message);
      throw err;
    }

    // 2. Create room and attach event listeners
    const room = new Room();

    room.on(RoomEvent.ParticipantConnected, (participant) => {
      console.log(`[VoiceAgent] 👤 Participant joined: ${participant.identity}`);
    });

    room.on(RoomEvent.ParticipantDisconnected, (participant) => {
      console.log(`[VoiceAgent] 👤 Participant left: ${participant.identity}`);
    });

    room.on(RoomEvent.TrackSubscribed, (track, publication, participant) => {
      console.log(`[VoiceAgent] 🔊 Subscribed to ${track.kind} track from ${participant.identity}`);
    });

    room.on(RoomEvent.TrackUnsubscribed, (track, publication, participant) => {
      console.log(`[VoiceAgent] 🔇 Unsubscribed from ${track.kind} track of ${participant.identity}`);
    });

    room.on(RoomEvent.Reconnecting, () => {
      console.log(`[VoiceAgent] ⚡ Reconnecting to room: ${roomName}`);
    });

    room.on(RoomEvent.Reconnected, () => {
      console.log(`[VoiceAgent] ✅ Reconnected to room: ${roomName}`);
    });

    room.on(RoomEvent.Disconnected, (reason) => {
      console.log(`[VoiceAgent] 🔌 Disconnected from room: ${roomName} (reason: ${reason || 'unknown'})`);
      this._cleanup(roomName);
    });

    // 3. Connect to room
    try {
      await room.connect(process.env.LIVEKIT_URL, token, {
        autoSubscribe: true,
      });
      console.log(`[VoiceAgent] ✅ Connected to room: ${roomName}`);
      console.log(`[VoiceAgent]    Participants in room: ${room.remoteParticipants.size + 1}`);
    } catch (err) {
      console.error(`[VoiceAgent] ❌ Failed to connect to room ${roomName}:`, err.message);
      throw err;
    }

    // 4. Store session reference (with safe timeout)
    const sessionTimer = setTimeout(() => {
      console.log(`[VoiceAgent] ⏱️ Session timeout reached (${timeoutMs}ms). Disconnecting.`);
      this.endSession(roomName).catch((err) => {
        console.error(`[VoiceAgent] Timeout disconnect failed for ${roomName}:`, err.message);
      });
    }, timeoutMs);

    this._activeSessions.set(roomName, { room, timer: sessionTimer });

    return { roomName, status: 'agent_connected' };
  }

  /**
   * Gracefully end a session and disconnect from the room.
   * @param {string} roomName
   */
  async endSession(roomName) {
    const session = this._activeSessions.get(roomName);
    if (!session) {
      console.log(`[VoiceAgent] No active session found for room: ${roomName}`);
      return;
    }

    try {
      await session.room.disconnect();
    } catch (err) {
      console.error(`[VoiceAgent] Error disconnecting from ${roomName}:`, err.message);
    }

    this._cleanup(roomName);
  }

  /**
   * Clean up session timer and map entry.
   * @param {string} roomName
   * @private
   */
  _cleanup(roomName) {
    const session = this._activeSessions.get(roomName);
    if (session) {
      clearTimeout(session.timer);
      this._activeSessions.delete(roomName);
    }
  }

  /**
   * Get count of active sessions (for debugging).
   * @returns {number}
   */
  getActiveSessionCount() {
    return this._activeSessions.size;
  }

  /**
   * Whether the native RTC module is available.
   * @returns {boolean}
   */
  isRtcAvailable() {
    return rtcAvailable;
  }
}

export default new VoiceAgentService();
